### ISSUE TITLE
第一次进行多方块结构创建后修改无法reload

### ISSUE THREAD

**Issue by xiaoliziawa** [CPearl0/Block-Crafting#2]
例子1:

BlockCrafting.addMultiblockStructure(MultiblockStructureBuilder.create("test1")
   .pattern('aaa','aaa','aaa')
   .pattern('aaa','a a','aaa')
   .pattern('aaa','aba','aaa')
   .where('a','cobblestone')
   .center('b','campfire')
   .craftingItem('minecraft:stick')
   .result('100x minecraft:diamond')
   .build()
)

例子2:

BlockCrafting.addMultiblockStructure(MultiblockStructureBuilder.create("test1")
   .pattern('aaa','aaa','aaa')
   .pattern('aaa','aaa','aaa')
   .pattern('aaa','aaa','aaa')
   .center('a','campfire')
   .craftingItem('minecraft:stick')
   .result('100x minecraft:diamond')
   .build()
)

这是两个例子,
意思是首次在例子1创建后来更改代码变成例子2
可是在游戏内输入kubejs reload指令后无法重新加载到例子2
重载完成后保留的仍然是例子1的结构,而例子2的结构无效

**Comment by xiaoliziawa** [comment]
reload也不起作用

**Comment by CPearl0** [comment]
Your script has some errors.
Use "minecraft:cobblestone".
add
```JavaScript
    .where(' ', Blocks.AIR)
```
